[workspace]
members = [
  ".",
  "rain-lang"
, "range-enum"]

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
tracing = "0.1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
# unwrap_used = "warn"
nursery = "warn"
cargo = "warn"
missing_const_for_fn = "allow"

[package]
name = "rain"
version.workspace = true
edition.workspace = true
description = "Well it certainly looks like a build system"
authors = ["Ruairidh Williamson"]
readme = "readme.md"
publish = false

[profile.release]
lto = true

[lints]
workspace = true

[dependencies]
rain-lang = { path = "rain-lang" }

tracing.workspace = true

clap = { version = "4.5", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
owo-colors = "4.0.0"
dirs = "5.0.1"
serde = { version = "1.0.197", features = ["derive"] }
toml = "0.8.12"
