[workspace]
members = [
  ".",
  "rain-lang",
  "range-enum",
]

[workspace.package]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
tracing = "0.1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
nursery = "warn"
cargo = "warn"
missing_const_for_fn = "allow"
# unwrap_used = "warn"

[package]
name = "rain"
version.workspace = true
edition.workspace = true
description = "Well it certainly looks like a build system"
authors = ["Ruairidh Williamson"]
readme = "readme.md"
publish = false

[profile.release]
lto = true

[lints]
workspace = true

[dependencies]
rain-lang = { path = "rain-lang" }

clap.workspace = true
serde.workspace = true
tracing.workspace = true

dialoguer = { version = "0.11", default_features = false }
dirs = "5.0"
owo-colors = "4.0"
thiserror = "1.0"
toml = "0.8"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.8", features = ["v4"] }
walkdir = "2.5"
