[workspace]
members = [
  ".",
  "rain-lang"
]

[workspace.package]
version = "0.0.0"
edition = "2021"

[package]
name = "rain"
version.workspace = true
edition.workspace = true

[dependencies]
rain-lang = { path = "rain-lang" }

clap = { version = "4.5", features = ["derive"] }
