[package]
name = "rain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
env_logger.workspace = true
humansize = "2.1.3"
inquire = "0.7.5"
log.workspace = true
rain-core = { path = "../core" }
serde.workspace = true
termcolor.workspace = true
