[package]
name = "rain-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
chrono.workspace = true
ciborium = "0.2.2"
dircpy = { version = "0.3.19", default-features = false }
dirs = "6.0.0"
env_logger.workspace = true
libc.workspace = true
log.workspace = true
num-bigint = "0.4.6"
reqwest = { version = "0.12.9", features = ["blocking"] }
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
web-time.workspace = true
zip = "2.2.0"

poison_panic.path = "../poison_panic"
rain-lang.path = "../lang"

[dev-dependencies]
insta.workspace = true
quickcheck_macros.workspace = true
quickcheck.workspace = true
test-log.workspace = true
