[package]
name = "rain-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
ciborium = "0.2.2"
colored.workspace = true
dircpy = { version = "0.3.19", default-features = false }
dirs = "5.0.1"
env_logger.workspace = true
log.workspace = true
lru = "0.12.4"
num-bigint = "0.4.6"
reqwest = { version = "0.12.9", features = ["blocking"] }
serde.workspace = true
uuid.workspace = true
zip = "2.2.0"
web-time.workspace = true
thiserror.workspace = true

rain-lang.path = "../lang"

[dev-dependencies]
insta.workspace = true
quickcheck_macros.workspace = true
quickcheck.workspace = true
test-log.workspace = true
