[package]
name = "rain-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
chrono = "0.4.38"
colored = "2.1.0"
dircpy = { version = "0.3.19", default-features = false }
dirs = "5.0.1"
env_logger.workspace = true
log.workspace = true
lru = "0.12.4"
num-bigint = "0.4.6"
reqwest = { version = "0.12.9", features = ["blocking"] }
serde.workspace = true
uuid.workspace = true
zip = "2.2.0"

[dev-dependencies]
insta = { version = "1.39.0", features = ["colors"], default-features = false }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
