[package]
name = "rain-ci-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
postgres-types = { version = "0.2.11", features = ["derive", "with-uuid-1", "with-chrono-0_4"] }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true, features = ["v4"] }

[lints]
workspace = true
