[package]
name = "rain-lang"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
colored = "2.1.0"
lru = "0.12.4"
num-bigint = "0.4.6"

[dev-dependencies]
anyhow.workspace = true
insta = { version = "1.39.0", features = ["colors"], default-features = false }
