[package]
name = "rain-lang"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
colored = "2.1.0"
dirs = "5.0.1"
dircpy = { version = "0.3.19", default-features = false }
lru = "0.12.4"
num-bigint = "0.4.6"
uuid.workspace = true
zip = "2.2.0"

[dev-dependencies]
insta = { version = "1.39.0", features = ["colors"], default-features = false }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
