[package]
name = "rain-lang"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[dev-dependencies]
insta = { version = "1.39.0", features = ["colors"], default-features = false }

[lints]
workspace = true
