[package]
name = "rain-lang"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[dev-dependencies]
insta = "1.39.0"

[lints]
workspace = true
