name: rain_ci

services:
  web:
    build:
      context: ../
      dockerfile: ci/web/Containerfile
    environment:
      - RUST_LOG=info
      - ADDR=0.0.0.0:3000
      - GITHUB_OAUTH_FILE=/run/secrets/github_oauth
      - ALLOWED_GITHUB_USER_ID=43679745
      - ALLOWED_GITHUB_LOGIN=RuairidhWilliamson
      - DB_HOST=db
      - DB_NAME=rain
      - DB_USER=rain
      - DB_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - github_oauth
      - postgres_password
    ports:
      - 3000:3000
    depends_on:
      migrator:
        condition: service_completed_successfully

  coordinator:
    build:
      context: ../
      dockerfile: ci/coordinator/Containerfile
    environment:
      - RUST_LOG=info
      - ADDR=127.0.0.1:3000
    depends_on:
      migrator:
        condition: service_completed_successfully

  migrator:
    build:
      context: ../
      dockerfile: ci/migrator/Containerfile
    environment:
      - DB_HOST=db
      - DB_NAME=rain
      - DB_USER=rain
      - DB_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    depends_on:
      db:
        condition: service_healthy

  db:
    image: docker.io/postgres:alpine
    shm_size: 128mb
    environment:
      - POSTGRES_DB=rain
      - POSTGRES_USER=rain
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

secrets:
  github_oauth:
    file: ./secrets/github_oauth.json
  postgres_password:
    file: ./secrets/postgres_password.txt
