name: rain_ci

services:
  web:
    build:
      context: ../
      dockerfile: ci/web/Containerfile
    environment:
      - RUST_LOG=info
      - ADDR=0.0.0.0:3000
      - GITHUB_OAUTH_FILE=/run/secrets/github_oauth
      - ALLOWED_GITHUB_USER_ID=43679745
      - ALLOWED_GITHUB_LOGIN=RuairidhWilliamson
      - DB_HOST=db
      - DB_NAME=rain
      - DB_USER=rain
      - DB_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - github_oauth
      - postgres_password
    ports:
      - 3000:3000
    depends_on:
      - db

  coordinator:
    build:
      context: ../
      dockerfile: ci/coordinator/Containerfile
    environment:
      - RUST_LOG=info
      - ADDR=127.0.0.1:3000
    depends_on:
      - db

  db:
    image: docker.io/postgres:alpine
    shm_size: 128mb
    environment:
      - POSTGRES_DB=rain
      - POSTGRES_USER=rain
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

secrets:
  github_oauth:
    file: ./secrets/github_oauth.json
  postgres_password:
    file: ./secrets/postgres_password.txt
