[package]
name = "rain-ci-coordinator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.22.1"
bytes.workspace = true
dotenvy.workspace = true
envy = "0.4.2"
octocrab = { version = "0.44.0" }
serde_json.workspace = true
serde.workspace = true
webhook-forwarder = { git = "https://github.com/RuairidhWilliamson/webhook-forwarder.git", default-features = false }
tokio = { version = "1.36.0", features = ["full"] }
tracing-subscriber.workspace = true
tracing.workspace = true
url.workspace = true
rain-core = { path = "../../core" }
rain-lang = { path = "../../lang" }
http-body-util = "0.1.3"
tokio-stream = "0.1.17"
tokio-util = { version = "0.7.14", features = ["io"] }
poison_panic.path = "../../poison_panic"
ring = { version = "0.17.14", features = ["std"] }
jsonwebtoken = { version = "9.3.1", default-features = false , features = ["use_pem"]}
chrono.workspace = true
sha2 = "0.10.8"
hex = "0.4.3"
cmov = "0.3.1"
