[package]
name = "rain-ci-coordinator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
base64 = "0.22.1"
bytes.workspace = true
dotenvy.workspace = true
envy = "0.4.2"
octocrab = { version = "0.43.0" }
serde_json.workspace = true
serde.workspace = true
smee-rs.path = "../../smee_rs"
tokio = { version = "1.36.0", features = ["full"] }
tracing-subscriber.workspace = true
tracing.workspace = true
url.workspace = true
rain-core = { path = "../../core" }
rain-lang = { path = "../../lang" }
http-body-util = "0.1.3"
tokio-stream = "0.1.17"
tokio-util = { version = "0.7.14", features = ["io"] }
